### PR TITLE
Change refs to new archive

### PR DESCRIPTION
**Pull request by borntohonk**

### CODE REVIEW

**Comment by kleo** [comment]
Hello! Thank you for the PR. Would you kindly consider utilizing the 1.0 tag from the original repository?

Checked my local copy and 1.0 was at: 

```
265e8f3e1987751ec41db6f1946d132b296aba43 - update readme
```

Latest commit is at:

```
3b1b2bc - Merge pull request #7
```

Some changes have been made to fusee-launcher.py before that commit

```
1502104 - Fix #20: Typo that still actually worked
49cf5f9 - Support FreeBSD via macOS backend
1a685c9 - Relocator default dir is now same as wherever fusee-launcher.py is
533343c - clean up dependencies for broader compatibility
```

**Comment by borntohonk** [comment]
Fixed, rebased commit/3b1b2bcca1b0e1f295e376b1dd8a1e582b18f41d

**Comment by kleo** [comment]
Kinda just wanted it separate from my project. Last request I promise ˢᵒʳʳʸ, please move 1.0 tag to 265e8f3. Thanks again for the mirror!

**Comment by borntohonk** [comment]
> Kinda just wanted it separate from my project. Last request I promise ˢᵒʳʳʸ, please move 1.0 tag to 265e8f3. Thanks again for the mirror!

The only difference between 265e8f3 and current debased master is 3 commits that all only edit text files. Not sure why you want to revert it to earlier commit over that

**Comment by kleo** [comment]
Brevity I guess

**Pull request merged**
